/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPackage;

import ijshockey.DBException;
import ijshockey.DriverManager;
import ijshockey.Owngoal;
import ijshockey.Speler;
import ijshockey.Wedstrijd;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ekmaes
 */
public class AddHighlight extends javax.swing.JFrame {

    public static DriverManager dManager;
    private Wedstrijd wedstrijd;
    DefaultListModel DLM;

    /**
     * Creates new form AddHighlight
     */
    public AddHighlight() {
        initComponents();
    }

    public AddHighlight(DriverManager dManager, Wedstrijd wed) {
        AddHighlight.dManager = dManager;
        this.wedstrijd = wed;
        initComponents();
        setLocationRelativeTo(null);
        this.setjLabelTop("Opstelling wedstrijd :" + wed.getWedstrijdNr() + " : " + wed.getThuisTeam().getNaam() + " versus " + wed.getUitTeam().getNaam());

    }

    private void FillLijstSpelertjesThuis(DefaultListModel DLM) {
        try {

            jListSpeler.setModel(DLM);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void FillLijstSpelertjesUit(DefaultListModel DLM) {
        try {

            jListSpeler.setModel(DLM);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSpeler = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jTextMinuut = new javax.swing.JTextField();
        GoalButton = new javax.swing.JButton();
        OwngoalButton = new javax.swing.JButton();
        PenaltyButton = new javax.swing.JButton();
        StrafButton = new javax.swing.JButton();
        VorigeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonThuisTeam = new javax.swing.JRadioButton();
        jRadioButtonUitTeam = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelTop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Highlight toevoegen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Speler:");

        jListSpeler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jListSpeler);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Minuut:");

        jTextMinuut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextMinuut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMinuutActionPerformed(evt);
            }
        });

        GoalButton.setBackground(java.awt.SystemColor.activeCaption);
        GoalButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GoalButton.setText("Goal");
        GoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoalButtonActionPerformed(evt);
            }
        });

        OwngoalButton.setBackground(java.awt.SystemColor.activeCaption);
        OwngoalButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OwngoalButton.setText("Owngoal");
        OwngoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwngoalButtonActionPerformed(evt);
            }
        });

        PenaltyButton.setBackground(java.awt.SystemColor.activeCaption);
        PenaltyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PenaltyButton.setText("Penalty");
        PenaltyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenaltyButtonActionPerformed(evt);
            }
        });

        StrafButton.setBackground(java.awt.SystemColor.activeCaption);
        StrafButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StrafButton.setText("Straf");
        StrafButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrafButtonActionPerformed(evt);
            }
        });

        VorigeButton.setBackground(new java.awt.Color(255, 204, 204));
        VorigeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VorigeButton.setText("Vorige");
        VorigeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VorigeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kies soort highlight");

        buttonGroup1.add(jRadioButtonThuisTeam);
        jRadioButtonThuisTeam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonThuisTeam.setText("Thuis");
        jRadioButtonThuisTeam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonThuisTeamStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonUitTeam);
        jRadioButtonUitTeam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonUitTeam.setText("Uit");
        jRadioButtonUitTeam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonUitTeamStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Team:");

        jLabelTop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTop.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonUitTeam)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRadioButtonThuisTeam))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(GoalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(OwngoalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(PenaltyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(StrafButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(VorigeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jTextMinuut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabelTop)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GoalButton, OwngoalButton, PenaltyButton, StrafButton, VorigeButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonThuisTeam)
                    .addComponent(jRadioButtonUitTeam))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMinuut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwngoalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PenaltyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StrafButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VorigeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VorigeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VorigeButtonActionPerformed

        AddOpstelling updateForm = null;
        try {
            updateForm = new AddOpstelling(dManager, wedstrijd);
        } catch (SQLException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VorigeButtonActionPerformed

    private void GoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoalButtonActionPerformed
        String listValue = (String) jListSpeler.getSelectedValue();
        String[] array = listValue.split("-");
        String lidnrStr = array[array.length - 1].trim();
        int lidnr = Integer.parseInt(lidnrStr);
        Speler speler = null;
        try {
            speler = DriverManager.getSpeler(lidnr);
        } catch (DBException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        int minuut = Integer.parseInt(jTextMinuut.getText());
        AddGoal updateForm = null;
        try {
            updateForm = new AddGoal(dManager, wedstrijd, speler, minuut);
        } catch (SQLException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_GoalButtonActionPerformed

    private void PenaltyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenaltyButtonActionPerformed
        // TODO add your handling code here:

        String listValue = (String) jListSpeler.getSelectedValue();
        String[] array = listValue.split("-");
        String lidnrStr = array[array.length - 1].trim();
        int lidnr = Integer.parseInt(lidnrStr);
        Speler speler = null;
        try {
            speler = DriverManager.getSpeler(lidnr);
        } catch (DBException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }

        int minuut = Integer.parseInt(jTextMinuut.getText());

        AddPenalty updateForm = new AddPenalty(dManager, wedstrijd, speler, minuut);
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PenaltyButtonActionPerformed

    private void StrafButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrafButtonActionPerformed

        String listValue = (String) jListSpeler.getSelectedValue();
        String[] array = listValue.split("-");
        String lidnrStr = array[array.length - 1].trim();
        int lidnr = Integer.parseInt(lidnrStr);
        Speler speler = null;
        try {
            speler = DriverManager.getSpeler(lidnr);
        } catch (DBException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }

        int minuut = Integer.parseInt(jTextMinuut.getText());

        AddStraf updateForm = new AddStraf(dManager, wedstrijd, speler, minuut);
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StrafButtonActionPerformed

    private void OwngoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwngoalButtonActionPerformed
        // TODO add your handling code here:

        String listValue = (String) jListSpeler.getSelectedValue();
        String[] array = listValue.split("-");
        String lidnrStr = array[array.length - 1].trim();
        int lidnr = Integer.parseInt(lidnrStr);
        Speler speler = null;
        try {
            speler = DriverManager.getSpeler(lidnr);
        } catch (DBException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }

        int minuut = Integer.parseInt(jTextMinuut.getText());

        Owngoal og = null;

        try {
            og = new Owngoal(minuut, speler, wedstrijd);
            DriverManager.addOwngoal(og);
            this.jTextMinuut.setText("");
            JOptionPane.showMessageDialog(null, "Owngoal opgeslaan");
        } catch (DBException ex) {
            Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OwngoalButtonActionPerformed

    private void jRadioButtonUitTeamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonUitTeamStateChanged
        if (jRadioButtonUitTeam.isSelected()) {
            try {
                this.FillLijstSpelertjesUit(DriverManager.FillLijstSpelers(DLM, wedstrijd.getUitTeam().getStamNr()));
            } catch (SQLException ex) {
                Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jRadioButtonUitTeamStateChanged

    private void jRadioButtonThuisTeamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonThuisTeamStateChanged
        if (jRadioButtonThuisTeam.isSelected()) {
            try {
                this.FillLijstSpelertjesThuis(DriverManager.FillLijstSpelers(DLM, wedstrijd.getThuisTeam().getStamNr()));
            } catch (SQLException ex) {
                Logger.getLogger(AddHighlight.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jRadioButtonThuisTeamStateChanged

    private void jTextMinuutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMinuutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMinuutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHighlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHighlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHighlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHighlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHighlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoalButton;
    private javax.swing.JButton OwngoalButton;
    private javax.swing.JButton PenaltyButton;
    private javax.swing.JButton StrafButton;
    private javax.swing.JButton VorigeButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JList jListSpeler;
    private javax.swing.JRadioButton jRadioButtonThuisTeam;
    private javax.swing.JRadioButton jRadioButtonUitTeam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextMinuut;
    // End of variables declaration//GEN-END:variables

    private void setjLabelTop(String string) {
        this.jLabelTop.setText(string);
    }
}
