/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPackage;

import ijshockey.Competitie;
import ijshockey.DBException;
import ijshockey.DriverManager;
import ijshockey.Seizoen;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author favdndor
 */
public class GegevensOpvragen extends javax.swing.JFrame {

    public static DriverManager dManager;
    private Competitie competitie;
    private Seizoen seizoen;

    /**
     * Creates new form GegevensOpvragen
     */
    public GegevensOpvragen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    GegevensOpvragen(DriverManager dManager) {
        this.dManager = dManager;
        initComponents();
        setLocationRelativeTo(null);
    }

    GegevensOpvragen(DriverManager dManager, String competitienaam, int jaar) {
        this.dManager = dManager;
        this.competitie = DriverManager.getCompetitie(competitienaam);
        this.seizoen = DriverManager.getSeizoen(jaar, competitienaam);
        initComponents();
        setLocationRelativeTo(null);
        this.setjLabelTop("Gegevens opvragen van " + competitienaam + " seizoen : " + jaar);
    }

    GegevensOpvragen(DriverManager dManager, Competitie competitie, Seizoen seizoen) {
        this.dManager = dManager;
        this.competitie = competitie;
        this.seizoen = seizoen;
        initComponents();
        setLocationRelativeTo(null);
        this.setjLabelTop("Gegevens opvragen van " + competitie.getCompetitienaam() + " seizoen : " + seizoen.getJaar());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RankingTeamsButton = new javax.swing.JButton();
        RapportSpelerButton = new javax.swing.JButton();
        RapportTeamButton = new javax.swing.JButton();
        RankingSpelersButton = new javax.swing.JButton();
        VorigeButton = new javax.swing.JButton();
        jLabelTop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gegevens opvragen");

        RankingTeamsButton.setBackground(java.awt.SystemColor.activeCaption);
        RankingTeamsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RankingTeamsButton.setText("Klassement");
        RankingTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingTeamsButtonActionPerformed(evt);
            }
        });

        RapportSpelerButton.setBackground(java.awt.SystemColor.activeCaption);
        RapportSpelerButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RapportSpelerButton.setText("Rapport per speler");
        RapportSpelerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RapportSpelerButtonActionPerformed(evt);
            }
        });

        RapportTeamButton.setBackground(java.awt.SystemColor.activeCaption);
        RapportTeamButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RapportTeamButton.setText("Rapport per team");
        RapportTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RapportTeamButtonActionPerformed(evt);
            }
        });

        RankingSpelersButton.setBackground(java.awt.SystemColor.activeCaption);
        RankingSpelersButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RankingSpelersButton.setText("Topschutters");
        RankingSpelersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingSpelersButtonActionPerformed(evt);
            }
        });

        VorigeButton.setBackground(new java.awt.Color(255, 204, 204));
        VorigeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VorigeButton.setText("Vorige");
        VorigeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VorigeButtonActionPerformed(evt);
            }
        });

        jLabelTop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VorigeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RankingSpelersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RapportTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RapportSpelerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RankingTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addComponent(jLabelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RankingTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RankingSpelersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RapportTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RapportSpelerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(VorigeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RapportTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RapportTeamButtonActionPerformed
        RapportTeam updateForm = null;

        try {
            updateForm = new RapportTeam(dManager, competitie, seizoen);
        } catch (SQLException ex) {
            Logger.getLogger(GegevensOpvragen.class.getName()).log(Level.SEVERE, null, ex);
        }

        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RapportTeamButtonActionPerformed

    private void RapportSpelerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RapportSpelerButtonActionPerformed
        RapportSpeler updateForm = null;
        try {
            updateForm = new RapportSpeler(dManager, competitie, seizoen);
        } catch (SQLException ex) {
            Logger.getLogger(GegevensOpvragen.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RapportSpelerButtonActionPerformed

    private void RankingTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingTeamsButtonActionPerformed
        TeamRanking updateForm = null;
        try {
            updateForm = new TeamRanking(dManager, competitie, seizoen);
        } catch (DBException ex) {
            Logger.getLogger(GegevensOpvragen.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RankingTeamsButtonActionPerformed

    private void VorigeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VorigeButtonActionPerformed
        CompetitieOpvragen updateForm = null;
        try {
            updateForm = new CompetitieOpvragen(dManager);
        } catch (DBException ex) {
            Logger.getLogger(GegevensOpvragen.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_VorigeButtonActionPerformed

    private void RankingSpelersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingSpelersButtonActionPerformed
        SpelerRanking updateForm = null;
        try {
            updateForm = new SpelerRanking(dManager, competitie, seizoen);
        } catch (DBException ex) {
            Logger.getLogger(GegevensOpvragen.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RankingSpelersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GegevensOpvragen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GegevensOpvragen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GegevensOpvragen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GegevensOpvragen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GegevensOpvragen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RankingSpelersButton;
    private javax.swing.JButton RankingTeamsButton;
    private javax.swing.JButton RapportSpelerButton;
    private javax.swing.JButton RapportTeamButton;
    private javax.swing.JButton VorigeButton;
    private javax.swing.JLabel jLabelTop;
    // End of variables declaration//GEN-END:variables

    private void setjLabelTop(String string) {
        this.jLabelTop.setText(string);
    }
}
